### ISSUE TITLE
New website for camp.etherisc.com

### ISSUE THREAD

**Issue by kpii** [etherisc/hackathon#3]
http://camp.etherisc.com needs a new start

**Comment by lopezi** [comment]
There is work in progress at:
http://etherisc.lopezi.biz/

WHITE PAPER
Needs a first final version before publish online.

DAPPS
Missing links to the apps

TEAM
I put the 3 guys from the camp on the website. Further team members to be decided by the founders. I am interested in joining the team.

HACKATON
Image with link to the camp site.

INVESTORS
Do we need this at this point?

TIMELINE
A timeline of events

PRESS
Etherisc on the press


CONSIDERATIONS
Please review the current content, suggest modifications, content to remove, content to add, etc…
